# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftGuard < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/pgomes13/drift-guard-engine"
  version "1.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v1.1.6/drift-guard_1.1.6_darwin_amd64.tar.gz"
      sha256 "9049449e2b9054ee63558dab3905a74393f95f68175047d23fcb979a55cf649c"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v1.1.6/drift-guard_1.1.6_darwin_arm64.tar.gz"
      sha256 "03f43912dcb4e4c3a079a775a2c9bf38ad29fb879ae0cd916f25bdf1e2c4d2b1"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v1.1.6/drift-guard_1.1.6_linux_amd64.tar.gz"
      sha256 "452f918c35c55f359ee517f2659c48a01b0b7b242bd1c5a46cfcb5cd802bfab6"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v1.1.6/drift-guard_1.1.6_linux_arm64.tar.gz"
      sha256 "88943a397276f6e38aab1866cffe34463e57eb30f6292cbfd4d5cae962f24bae"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  test do
    system "#{bin}/drift-guard", "--help"
  end
end
