# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftGuard < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/pgomes13/drift-guard-engine"
  version "2.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v2.6.4/drift-guard_2.6.4_darwin_amd64.tar.gz"
      sha256 "2ed2af6e76e44194d46a7f0b90279dc70abb1a1cc60aa76ff8f299fbf9457223"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v2.6.4/drift-guard_2.6.4_darwin_arm64.tar.gz"
      sha256 "32d4ce5ed05d7e1a35f3287c04d08476f8cc3d380380906f1cf8caa9a4daf730"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v2.6.4/drift-guard_2.6.4_linux_amd64.tar.gz"
      sha256 "3309b4e78f860de7ce1669480dcedfa3bb7e11d2784d37a729ab41e75723c12b"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgomes13/drift-guard-engine/releases/download/v2.6.4/drift-guard_2.6.4_linux_arm64.tar.gz"
      sha256 "d9650ef979046e28a678cb6abb6abcbf566b779caa66b589839775fcf5ee071d"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  test do
    system "#{bin}/drift-guard", "--help"
  end
end
